apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaforge

resources:
  - namespace.yaml
  - config.yaml
  - infra.yaml
  - observability.yaml
  - api-gateway.yaml
  - worker-image.yaml
  - worker-ocr.yaml
  - realtime-gateway.yaml

commonLabels:
  app.kubernetes.io/part-of: mediaforge
